### ISSUE TITLE
Make scipy.lat the canonical domain

### ISSUE THREAD

**Issue by astrojuanlu** [scipy-latinamerica/scipy-latinamerica.github.io#7]
We bought scipy.lat, so it would be nice to have:

- [x] https://www.scipy.lat -> main website
- [x] http://scipyla.org/conf/2019/ -> https://conf.scipy.lat -> latest conference
- [x] https://www.scipy.lat/conf/2018 -> past conferences

**Comment by xmnlab** [comment]
@arthuralvim changed the CNAME file .. but it seems the new domain is not working. what would be the next steps about this?

**Comment by astrojuanlu** [comment]
The two domains do not have the same configuration:

```
juanlu@ephyra:~$ dig scipy.lat +nostats +nocomments +nocmd
;scipy.lat.			IN	A
scipy.lat.		299	IN	A	104.27.163.118
scipy.lat.		299	IN	A	172.67.197.40
scipy.lat.		299	IN	A	104.27.162.118
juanlu@ephyra:~$ dig scipyla.org +nostats +nocomments +nocmd
;scipyla.org.			IN	A
scipyla.org.		299	IN	A	104.18.52.211
scipyla.org.		299	IN	A	172.67.170.94
scipyla.org.		299	IN	A	104.18.53.211
```

Not sure how to proceed.

**Comment by astrojuanlu** [comment]
I don't have access to the "settings" or the project nor the DNS configuration, not sure how can I help...

**Comment by xmnlab** [comment]
I sent you an invitation to the team yesterday ... let me know if I should send it again :)

**Comment by astrojuanlu** [comment]
I accepted it :) but still don't have "admin" access to this repository in particular

**Comment by xmnlab** [comment]
I change permission configurations for your user, let me know if it is working now :)

**Comment by astrojuanlu** [comment]
![Screenshot_2020-10-07 scipy-latinamerica scipy-latinamerica github io](https://user-images.githubusercontent.com/316517/95356997-95393300-08c7-11eb-8b47-1058b46e6083.png)

I don't think we can configure several domains on GitHub at the same time. Therefore, I'd say this requires coordinated action to avoid breaking any links:

- Make `scipy.lat` the canonical domain of this site (as outlined in my first comment here)
- Make `scipyla.org` redirect to `scipy.lat` with HTTP 301 Moved Permanently

So first, we need to

- Agree this is the way forward,
- Figure out who should make the configuration change on the `scipyla.org` side, and
- Coordinate a specific date to do the change

**Comment by xmnlab** [comment]
LGTM :) I will share this with the board group

**Comment by arthuralvim** [comment]
https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#cname-errors

**Comment by astrojuanlu** [comment]
- CNAME corrected, `scipy.lat` now redirects to the main website.
- @goanpeca is redirecting `scipyla.org` to `scipy.lat`
- @arthuralvim I guess we will need to create `conf.scipy.lat`

**Comment by astrojuanlu** [comment]
Also, we'll need to wait a few hours to re-enable HTTPS (updated first comment of this issue)

**Comment by astrojuanlu** [comment]
About HTTPS: I'm surprised to see 2 days after that it's still not available. None of the tips from https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#https-errors seems to apply to us. Any ideas?

**Comment by goanpeca** [comment]
>About HTTPS: I'm surprised to see 2 days after that it's still not available. 

@astrojuanlu it will not work since we use cloudfare. Github internaly uses fastly I think?

**Comment by astrojuanlu** [comment]
@goanpeca is taking care of the last tweaks and the HTTPS

**Comment by goanpeca** [comment]
@astrojuanlu made the fixes, we should be good now and using HTTPS all the time.

Please check!

**Comment by astrojuanlu** [comment]
Everything working! :tada: Closing! Thanks everyone :heart:
